//Metodos para Estados

POST http://localhost:4002/estados
content-type: application/json

{
    "id": "6",
    "nome": "Ceara",
    "sigla": "CE"
}

###
GET http://localhost:4002/estados

###
GET http://localhost:4002/estados/5


###
PUT http://localhost:4002/estados
content-type: application/json

{   
    "id": "5",
    "nome": "Santa Catarina",
    "sigla": "SC"
}

###
DELETE http://localhost:4002/estados/6


//Metodos para Cidade

###
POST http://localhost:4002/cidades
content-type: application/json

{   
    "id": "4",
    "nome": "Cidade Teste",
    "estado_id": "2"
}

###
GET http://localhost:4002/cidades

###
GET http://localhost:4002/cidades/3


###
PUT http://localhost:4002/cidades
content-type: application/json

{
    "id": "3",
    "nome": "Governador Valadares",
    "estado_id": "2"
}

###
DELETE http://localhost:4002/cidades/4


//Metodos para Tipos Sanguínos

###
POST http://localhost:4002/tiposSanguineos
content-type: application/json

    {
        "id": "4",
        "tipo": "AB",
        "fator": "Positivo"
    }

###
GET http://localhost:4002/tiposSanguineos
###
GET http://localhost:4002/tiposSanguineos/2

###
PUT http://localhost:4002/tiposSanguineos
content-type: application/json

    {
        "id": "3",
        "tipo": "O",
        "fator": "Negativo"    
    }


###
DELETE http://localhost:4002/tiposSanguineos/4


//Metodos para Locais de Coleta

###
POST http://localhost:4002/locaisColeta
content-type: application/json

   {
        "id": "4",
        "nome": "Minha Casa",
        "rua": "Rua 36",
        "numero": "115",
        "complemento": "Centro",
        "cidade_id": "1"
    }

###
GET http://localhost:4002/locaisColeta

###
GET http://localhost:4002/locaisColeta/2

###
PUT http://localhost:4002/locaisColeta
content-type: application/json
    
    {
        "id": "2",
        "nome": "UFV",
        "rua": "Rua 36",
        "numero": "115",
        "complemento": "Loanda, João Monlevade",
        "cidade_id": "2"
    }

###
DELETE http://localhost:4002/locaisColeta/4


//Metodos para Pessoas

###
POST http://localhost:4002/pessoas
content-type: application/json

    {
        "id": "3",
        "nome": "Lucas Horta Monteiro de Castro",
        "rua": "Rua 86", 
        "numero": "203",
        "complemento": "Novo Horizonte, Timóteo", 
        "documento": "MG-43.323.431",
        "cidade_id": "3",
        "tipoSanguineo_id": "3"
    } 

###
GET http://localhost:4002/pessoas
###
GET http://localhost:4002/pessoas/3

###
PUT http://localhost:4002/pessoas
content-type: application/json

    {
        "id": "3",
        "nome": "João Pedro",
        "rua": "Rua 86", 
        "numero": "203",
        "complemento": "Novo Horizonte, Timóteo", 
        "documento": "MG-43.323.431",
        "cidade_id": "3",
        "tipo_id": "3"
    } 

###
DELETE http://localhost:4002/pessoas/3

//Metodos para Doacão

###
POST http://localhost:4002/doacoes
content-type: application/json

    {
      "id": "3",
      "data": "2022-10-14T02:29:59.683Z",
      "pessoa_id": "2",
      "local_id": "2"
    }

###
GET http://localhost:4002/doacoes

###
GET http://localhost:4002/doacoes/2

###
PUT http://localhost:4002/doacoes
content-type: application/json

    {
      "id": "2",
      "data": "2022-10-14T02:29:59.683Z",
      "pessoa_id": "2",
      "local_id": "2"
    }


###
DELETE http://localhost:4002/doacoes/3

