//Metodos para Estados

POST http://localhost:4002/estados
content-type: application/json

{
    "name": "Rio de Janeiro",
    "sigla": "RJ"
}

###
GET http://localhost:4002/estados

###
GET http://localhost:4002/estados/c9e134eb-097e-43a0-bcb7-9b73b4783ea0


###
PUT http://localhost:4002/estados/628f8fe6-cbf4-447a-9cc9-bb92c59cc81f
content-type: application/json

{
    "name": "Minas Gerais",
    "sigla": "MG"
}


###
DELETE http://localhost:4002/estados/628f8fe6-cbf4-447a-9cc9-bb92c59cc81f


//Metodos para Cidade

###
POST http://localhost:4002/cidades
content-type: application/json

{
    "name": "Timóteo",
    "estado_id": "7cf8276e-e72a-43d1-bce7-3b3d65a24a4a"
}

###
GET http://localhost:4002/cidades

###
GET http://localhost:4002/cidades/5b6e94d7-7dce-4628-8192-9d22f2be89c0


###
PUT http://localhost:4002/cidades/0a3fb57c-dbc0-4701-882b-7d738ffd963b
content-type: application/json

{
    "name": "Jurere",
    "estado_id": "7cf8276e-e72a-43d1-bce7-3b3d65a24a4a"
}


###
DELETE http://localhost:4002/cidades/0a3fb57c-dbc0-4701-882b-7d738ffd963b


//Metodos para Doacão

###
POST http://localhost:4002/doacoes
content-type: application/json

    {
      "data": "11/10/2022",
      "pessoa_id": "544490c0-628c-4f65-b278-15236ae9b848",
      "local_id": "544490c0-628c-4f65-b278-15236ae9b848"
    }

###
GET http://localhost:4002/doacoes

###
GET http://localhost:4002/doacoes/e3aa0fc3-baee-4cb6-915d-b028788b0bfd

###
PUT http://localhost:4002/doacoes/e3aa0fc3-baee-4cb6-915d-b028788b0bfd
content-type: application/json

    {
      "data": "13/10/2022",
      "pessoa_id": "544490c0-628c-4f65-b278-15236ae9b848",
      "local_id": "544490c0-628c-4f65-b278-15236ae9b848"
    }

###
DELETE http://localhost:4002/doacoes/e3aa0fc3-baee-4cb6-915d-b028788b0bfd


//Metodos para Locais de Coleta

###
POST http://localhost:4002/locaisColeta
content-type: application/json

   {
        "name": "UFMG",
        "rua": "Rua 36",
        "numero": "115",
        "complemento": "Loanda, João Monlevade",
        "cidade_id": "5b6e94d7-7dce-4628-8192-9d22f2be89c0"
    }

###
GET http://localhost:4002/locaisColeta

###
GET http://localhost:4002/locaisColeta/ab9bf908-9027-4bc8-a588-a13f0a4c708e

###
PUT http://localhost:4002/locaisColeta/9df98cbb-b4e1-460a-a8a7-11895579becc
content-type: application/json
    
    {
        "name": "UFV",
        "rua": "Rua 36",
        "numero": "115",
        "complemento": "Loanda, João Monlevade",
        "cidade_id": "5b6e94d7-7dce-4628-8192-9d22f2be89c0"
    }

###
DELETE http://localhost:4002/locaisColeta/ab9bf908-9027-4bc8-a588-a13f0a4c708e



//Metodos para Pessoas

###
POST http://localhost:4002/pessoas
content-type: application/json

    {
        "name": "Maria Horta Monteiro de Castro",
        "rua": "Rua 86", 
        "numero": "203",
        "complemento": "Novo Horizonte, Timóteo", 
        "documento": "MG-43.323.431",
        "cidade_id": "f1b9cd97-a9a2-4ee2-a495-d0403ec60f20",
        "tipo_id": ""
    } 

###
GET http://localhost:4002/pessoas/
###
GET http://localhost:4002/pessoas/b4ab981e-339f-43b3-b092-4216ff026dab

###
PUT http://localhost:4002/pessoas/b4ab981e-339f-43b3-b092-4216ff026dab
content-type: application/json

    {
        "name": "Jose Horta Monteiro de Castro",
        "rua": "Rua 86", 
        "numero": "203",
        "complemento": "Novo Horizonte, Timóteo", 
        "documento": "MG-43.323.431",
        "cidade_id": "f1b9cd97-a9a2-4ee2-a495-d0403ec60f20",
        "tipo_id": ""
    } 

###
DELETE http://localhost:4002/pessoas/b4ab981e-339f-43b3-b092-4216ff026dab


//Metodos para Tipos Sanguínos

###
POST http://localhost:4002/tipossanguineos
content-type: application/json

    {
        "tipo": "O",
        "fator": "R"
    }

###
GET http://localhost:4002/tipossanguineos/
###
GET http://localhost:4002/tipossanguineos/76a16136-424b-4bbb-9eed-9869623637ad

###
PUT http://localhost:4002/tipossanguineos/76a16136-424b-4bbb-9eed-9869623637ad
content-type: application/json

    {
        "tipo": "A",
        "fator": "R+"    
    }
###
DELETE http://localhost:4002/tipossanguineos/76a16136-424b-4bbb-9eed-9869623637ad


