//Metodos para Estados

###
POST http://localhost:4002/estados
content-type: application/json

{
    "nome": "São Paulo",
    "sigla": "SP"
}

###
GET http://localhost:4002/estados

###
GET http://localhost:4002/estados/6


###
PUT http://localhost:4002/estados
content-type: application/json

{   
    "id": "6",
    "nome": "Maranhão",
    "sigla": "MA"
}

###
DELETE http://localhost:4002/estados/6


//Metodos para Cidade

###
POST http://localhost:4002/cidades
content-type: application/json

{   
    "nome": "São Paulo",
    "estado_id": "4"
}

###
GET http://localhost:4002/cidades

###
GET http://localhost:4002/cidades/3


###
PUT http://localhost:4002/cidades
content-type: application/json

{
    "id": "4",
    "nome": "Cidade de Deus",
    "estado_id": "1"
}

###
DELETE http://localhost:4002/cidades/4


//Metodos para Tipos Sanguínos

###
POST http://localhost:4002/tiposSanguineos
content-type: application/json

    {
        "tipo": "A",
        "fator": "Negativo"
    }

###
GET http://localhost:4002/tiposSanguineos
###
GET http://localhost:4002/tiposSanguineos/2

###
PUT http://localhost:4002/tiposSanguineos
content-type: application/json

    {
        "id": "3",
        "tipo": "AB",
        "fator": "Negativo"    
    }


###
DELETE http://localhost:4002/tiposSanguineos/4


//Metodos para Locais de Coleta

###
POST http://localhost:4002/locaisColeta
content-type: application/json

   {
        "nome": "Intituto De Coleta Sangue",
        "rua": "Rua 36",
        "numero": "115",
        "complemento": "Centro",
        "cidade_id": "2"
    }

###
GET http://localhost:4002/locaisColeta

###
GET http://localhost:4002/locaisColeta/2

###
PUT http://localhost:4002/locaisColeta
content-type: application/json
    
    {
        "id": "4",
        "nome": "Intituto de Coleta Joãozinho e Maria",
        "rua": "Rua 36",
        "numero": "115",
        "complemento": "Loanda, João Monlevade",
        "cidade_id": "2"
    }

###
DELETE http://localhost:4002/locaisColeta/4


//Metodos para Pessoas

###
POST http://localhost:4002/pessoas
content-type: application/json

    {
        "nome": "Lucas Horta Almeida",
        "rua": "Rua 86", 
        "numero": "203",
        "complemento": "Novo Horizonte, Timóteo", 
        "documento": "MG-43.323.431",
        "cidade_id": "1",
        "tipoSanguineo_id": "1"
    } 

###
GET http://localhost:4002/pessoas
###
GET http://localhost:4002/pessoas/3

###
PUT http://localhost:4002/pessoas
content-type: application/json

    {
        "id": "3",
        "nome": "João Pedro",
        "rua": "Rua 86", 
        "numero": "203",
        "complemento": "Novo Horizonte, Timóteo", 
        "documento": "MG-43.323.431",
        "cidade_id": "3",
        "tipo_id": "3"
    } 

###
DELETE http://localhost:4002/pessoas/3

//Metodos para Doacão

###
POST http://localhost:4002/doacoes
content-type: application/json

    {
      "date": "20/08/2022",
      "pessoa_id": "1",
      "local_id": "2"
    }

###
GET http://localhost:4002/doacoes

###
GET http://localhost:4002/doacoes/2

###
PUT http://localhost:4002/doacoes
content-type: application/json

    {
      "id": "2",
      "date": "25/10/2022",
      "pessoa_id": "1",
      "local_id": "1"
    }


###
DELETE http://localhost:4002/doacoes/1



//Metodos para Produtos

###
POST http://localhost:4002/produtos
content-type: application/json

    {
      "etiqueta": "Bolsa de Sangue",
      "validade": "20/10/2022",
      "doacao_id": "1"
    }

###
GET http://localhost:4002/produtos

###
GET http://localhost:4002/produtos/4

###
PUT http://localhost:4002/produtos
content-type: application/json

    {
      "id": "1",
      "etiqueta": "Pasta de Arquivamento",
      "validade": "25/10/2022",
      "doacao_id": "2"
    }


###
DELETE http://localhost:4002/produtos/4



//Metodos para Unidades

###
POST http://localhost:4002/unidades
content-type: application/json

    {
      "nome": "Unidade Médica Postinho",
      "numero": "14",
      "complemento": "Posto 3",
      "cidade_id": "2"
    }

###
GET http://localhost:4002/unidades

###
GET http://localhost:4002/unidades/3

###
PUT http://localhost:4002/unidades
content-type: application/json

    {
      "id": "3",
      "nome": "Unidade Médica Padre Lucas Castro",
      "numero": "104",
      "complemento": "Esquina 20",
      "cidade_id": "2"
    }


###
DELETE http://localhost:4002/unidades/3


//Metodos para Distribuicoes

###
POST http://localhost:4002/distribuicoes
content-type: application/json

    {
      "date": "22/10/2022",
      "produto_id": "1",
      "unidade_id": "2"
    }

###
GET http://localhost:4002/distribuicoes

###
GET http://localhost:4002/distribuicoes/2

###
PUT http://localhost:4002/distribuicoes
content-type: application/json

    {
      "id": "2",
      "date": "25/10/2022",
      "produto_id": "1",
      "unidade_id": "2"
    }

###
DELETE http://localhost:4002/distribuicoes/2
